"""Drift detector for docs/LLM-EMBEDDED-FAILURE-FACTORS.md → expert.md.

Why this is NOT a direct generator: `expert.md` is intentionally
abstract (principles, not API names) so that EmbedEval's discriminating
power is preserved. Auto-generating from FAILURE-FACTORS would
re-introduce specific APIs from the failure tables and push every
score toward 100% (see PLAN-context-quality-mode R3).

What this script does instead:

1. Parses the factor tables in FAILURE-FACTORS.md (sections A–F).
2. Emits `src/embedeval/context_packs/expert-coverage.md` — a
   machine-generated reference listing all factors by category and
   strength, suitable for humans to review against expert.md.
3. Exits non-zero when the generated file differs from the checked-in
   copy, letting CI catch FAILURE-FACTORS changes that haven't been
   reflected in the expert pack yet.

Usage:
    python scripts/build_expert_pack.py            # regenerate + exit 0 if clean
    python scripts/build_expert_pack.py --check    # CI gate (exit 1 on drift)
    python scripts/build_expert_pack.py --write    # force write (for local edits)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# The factor-table parser lives in the package so both this script and
# the `embedeval context-diagnose` command share a single source of
# truth. Tests that monkey-patch FACTORS_DOC need to reach through the
# module attribute, so we import the name rather than re-exporting.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from embedeval.failure_factors import (  # noqa: E402
    FACTORS_DOC,
    Category,
    Factor,
    parse_factors,
)

ROOT = Path(__file__).resolve().parent.parent
COVERAGE_OUT = ROOT / "src" / "embedeval" / "context_packs" / "expert-coverage.md"

# Re-export so existing tests that do `bep.Factor` / `bep.Category` /
# `bep.FACTORS_DOC` / `bep.parse_factors` keep working after the
# parser moved to src/embedeval/failure_factors.py.
__all__ = [
    "Category",
    "Factor",
    "FACTORS_DOC",
    "COVERAGE_OUT",
    "parse_factors",
    "render_coverage",
    "main",
]


def render_coverage(categories: list[Category]) -> str:
    """Render the coverage report — deterministic, stable across runs.

    The purpose is drift visibility: each category lists all factors in
    the order they appear in FAILURE-FACTORS.md, annotated with
    strength and evidence. A human reviewer cross-references this
    against expert.md to decide whether a new High-strength factor
    needs a new principle paragraph.
    """
    lines: list[str] = []
    lines.append("# Expert Pack Coverage Reference")
    lines.append("")
    lines.append(
        "Machine-generated by `scripts/build_expert_pack.py` from "
        "`docs/LLM-EMBEDDED-FAILURE-FACTORS.md`. **Do not edit by hand**"
        " — run the script."
    )
    lines.append("")
    lines.append(
        "Purpose: humans reviewing `src/embedeval/context_packs/expert.md` "
        "can scan this file to see whether every High-strength factor is "
        "represented (as a principle, not an API) in the curated pack."
    )
    lines.append("")
    total = sum(len(c.factors) for c in categories)
    high = sum(1 for c in categories for f in c.factors if f.strength == "High")
    lines.append(
        f"**Factors:** {total} total across {len(categories)} categories "
        f"({high} High-strength — the must-cover set)"
    )
    lines.append("")
    for cat in categories:
        lines.append(f"## {cat.letter}. {cat.title}")
        lines.append("")
        lines.append("| # | Factor | Strength | Evidence |")
        lines.append("|---|--------|----------|----------|")
        for f in cat.factors:
            lines.append(f"| {f.factor_id} | {f.name} | {f.strength} | {f.evidence} |")
        lines.append("")
        high_in_cat = [f for f in cat.factors if f.strength == "High"]
        if high_in_cat:
            lines.append(
                "**High-strength (must be represented in expert.md):** "
                + ", ".join(f.factor_id for f in high_in_cat)
            )
            lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="CI mode: exit 1 if the checked-in file differs from the "
        "regenerated output. Does not write.",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Force-write the coverage file even when it matches.",
    )
    args = parser.parse_args(argv)

    # Re-read FACTORS_DOC via this module's attribute so tests that
    # monkey-patch `build_expert_pack.FACTORS_DOC` still override the
    # path even though the default value was imported from the package.
    markdown = _current("FACTORS_DOC").read_text(encoding="utf-8")
    categories = parse_factors(markdown)
    if not categories:
        rel = _current("FACTORS_DOC").relative_to(ROOT)
        print(
            f"ERROR: no A–F category sections parsed from {rel} "
            "— doc structure may have changed",
            file=sys.stderr,
        )
        return 2

    rendered = render_coverage(categories)
    out_path = _current("COVERAGE_OUT")  # re-read so monkeypatched tests see the swap
    existing = out_path.read_text(encoding="utf-8") if out_path.is_file() else ""

    def _display(p: Path) -> str:
        try:
            return str(p.relative_to(ROOT))
        except ValueError:
            return str(p)

    if args.check:
        if rendered != existing:
            print(
                "DRIFT: expert-coverage.md is out of sync with "
                "LLM-EMBEDDED-FAILURE-FACTORS.md.\n"
                "Run `python scripts/build_expert_pack.py` locally, "
                "verify the diff, then commit the regenerated file.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {_display(out_path)} is in sync.")
        return 0

    if rendered == existing and not args.write:
        print(f"OK: {_display(out_path)} already up to date.")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote {_display(out_path)}")
    return 0


def _current(name: str) -> Path:
    """Look up a module-level Path attribute at call time rather than
    import time. Tests monkeypatch `bep.FACTORS_DOC` / `bep.COVERAGE_OUT`
    after import; binding the reference through this shim keeps the
    override visible to `main`."""
    return globals()[name]


if __name__ == "__main__":
    sys.exit(main())
